SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS') FROM DUAL;

SELECT DATA_DE_NASCIMENTO, TO_CHAR(DATA_DE_NASCIMENTO, 'DD MONTH YYYY, DAY') FROM TABELA_DE_CLIENTES;

SELECT SYSDATE + 127 FROM DUAL;

SELECT DATA_DE_NASCIMENTO, IDADE, (SYSDATE - DATA_DE_NASCIMENTO) / 365 AS idade FROM TABELA_DE_CLIENTES;


SELECT MONTHS_BETWEEN(SYSDATE, DATA_DE_NASCIMENTO) FROM TABELA_DE_CLIENTES;

SELECT ADD_MONTHS(SYSDATE, 10) FROM DUAL;SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS') FROM DUAL;

SELECT DATA_DE_NASCIMENTO, TO_CHAR(DATA_DE_NASCIMENTO, 'DD MONTH YYYY, DAY') FROM TABELA_DE_CLIENTES;

SELECT SYSDATE + 127 FROM DUAL;

SELECT DATA_DE_NASCIMENTO, IDADE, (SYSDATE - DATA_DE_NASCIMENTO) / 365 AS idade FROM TABELA_DE_CLIENTES;


SELECT MONTHS_BETWEEN(SYSDATE, DATA_DE_NASCIMENTO) FROM TABELA_DE_CLIENTES;

SELECT ADD_MONTHS(SYSDATE, 10) FROM DUAL;