commit;

SELECT NOME, LOWER(NOME), UPPER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

SELECT ENDERECO_1, BAIRRO, CONCAT(CONCAT(ENDERECO_1, ' '), BAIRRO) FROM TABELA_DE_CLIENTES;

SELECT ENDERECO_1 || ' ' || BAIRRO FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 70, '*') FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO, 70, '*') FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO, 3, 5) FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, 'Campo') FROM TABELA_DE_PRODUTOS;

SELECT '     VIC    ' AS X, LTRIM('     VIC    ') AS Y FROM DUAL;
SELECT '     VIC    ' AS X, LTRIM('     VIC    ') AS Y, RTRIM('     VIC    ') AS Z FROM DUAL;
SELECT '     VIC    ' AS X, LTRIM('     VIC    ') AS Y, RTRIM('     VIC    ') AS Z, TRIM('     VIC    ') AS W FROM DUAL;


SELECT NOME_DO_PRODUTO, REPLACE(REPLACE(NOME_DO_PRODUTO, 'Litro', 'L'), 'Ls', 'L') FROM TABELA_DE_PRODUTOS