SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1040107';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Melancia';


SELECT * FROM TB_CLIENTES WHERE IDADE = 18;
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = '25/03/92';
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('25/03/1992', 'DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('03/25/1992', 'MM/DD/YYYY');

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16 AND PRECO_LISTA <= 21