GRANT EXECUTE ON ATUALIZAR_CLI_SEG_MERCADO TO user_app;
GRANT EXECUTE ON ATUALIZAR_FATURAMENTO_PREVISTO TO user_app;
GRANT EXECUTE ON EXCLUIR_CLIENTE TO user_app;
GRANT EXECUTE ON INCLUIR_CLIENTE TO user_app;

GRANT SELECT ON CLIENTE TO user_app;


SELECT * FROM CLIENTE;
rollback;

call USER_DEV.INCLUIR_CLIENTE(5, 'Padaria', '22220', 1, 80000);