CREATE PROCEDURE proc_incluir_segmercado(p_ID IN NUMBER, p_DESCRICAO IN VARCHAR2)
IS
BEGIN
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
    COMMIT;
END;

SELECT * FROM SEGMERCADO;
CALL proc_incluir_segmercado(10, 'FARMÁCIA');