DECLARE
    v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type := 5000;
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
   IF v_FATURAMENTO <= 10000 THEN
       v_CATEGORIA := 'PEQUENO';
   ELSIF v_FATURAMENTO <= 50000 THEN
       v_CATEGORIA := 'MÉDIO';
   ELSIF v_FATURAMENTO <= 100000 THEN
       v_CATEGORIA := 'MÉDIO GRANDE';
   ELSE
       v_CATEGORIA := 'GRANDE';
   END IF;
   DBMS_OUTPUT.put_line(v_CATEGORIA);
END;


CREATE OR REPLACE FUNCTION categoria_cliente(p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%type)
    RETURN CLIENTE.CATEGORIA%type
IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
    IF p_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF p_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF p_FATURAMENTO <= 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE
        v_CATEGORIA := 'GRANDE';
    END IF;
    RETURN v_CATEGORIA;
END;

SELECT 1, CATEGORIA_CLIENTE(1000) FROM DUAL;
