SELECT * FROM SEGMERCADO;
DECLARE
    v_ID        SEGMERCADO.ID%type     := 3;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Industria';
BEGIN
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO);
    COMMIT;
END;


