SELECT * FROM SEGMERCADO;
DECLARE
    v_ID        SEGMERCADO.ID%type     := 1;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'varejista';
BEGIN
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
    v_ID := 3;
    v_DESCRICAO := 'Industrialista';
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(v_DESCRICAO) WHERE ID = v_ID;
    COMMIT;
END;


