CREATE OR REPLACE PROCEDURE incluir_cliente(
    p_ID CLIENTE.ID%type,
    p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
    p_CNPJ CLIENTE.CNPJ%type,
    p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
    p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
    IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
    v_CNPJ CLIENTE.CNPJ%type;
    e_IDNULO EXCEPTION ;
    PRAGMA EXCEPTION_INIT(e_IDNULO, -1400);
    e_FATURAMENTO_NULO EXCEPTION;
BEGIN
    IF p_FATURAMENTO IS NULL THEN
        RAISE e_FATURAMENTO_NULO;
    END IF;
    v_CATEGORIA := CATEGORIA_CLIENTE(p_FATURAMENTO);
    FORMATA_CNPJ(p_CNPJ, v_CNPJ);

    INSERT INTO CLIENTE
    VALUES (p_ID, p_RAZAO, v_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
    COMMIT;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20010, 'Cliente já cadastrado');
        WHEN e_IDNULO THEN
            RAISE_APPLICATION_ERROR(-20015, 'Identificador nullo');
        WHEN e_FATURAMENTO_NULO THEN
            RAISE_APPLICATION_ERROR(-20015, 'Faturamento Nullo');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20020, 'Erro não esperado!! Texto Original: ' || SQLERRM());
END;

CALL INCLUIR_CLIENTE(9, 'Noovoo', '455545454', 6,null);
select * from CLIENTE;
select * from SEGMERCADO;
