CREATE OR REPLACE PROCEDURE incluir_cliente(
    p_ID CLIENTE.ID%type,
    p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
    p_CNPJ CLIENTE.CNPJ%type,
    p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
    p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
    IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
    v_CNPJ CLIENTE.CNPJ%type;
BEGIN
    v_CATEGORIA := CATEGORIA_CLIENTE(p_FATURAMENTO);
    FORMATA_CNPJ(p_CNPJ, v_CNPJ);

    INSERT INTO CLIENTE
    VALUES (p_ID, p_RAZAO, v_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
    COMMIT;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20010, 'Cliente já cadastrado');
END;

CALL INCLUIR_CLIENTE(5, 'Noovoo', '455545454', 1,900000);
select * from CLIENTE;
