SELECT * FROM CLIENTES;
SELECT * FROM VENDEDORES;
SELECT * FROM PRODUTOS;
SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;
-- 1471156710
-- 235
-- 104100


SELECT N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
         INNER JOIN ITENS_NOTAS ITN ON ITN.NUMERO = N.NUMERO
GROUP BY N.DATA_VENDA;

CREATE TABLE TAB_FATURAMENTO(DATA_VENDA DATE NULL, FATURAMENTO FLOAT);

INSERT INTO TAB_FATURAMENTO
SELECT N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
FROM NOTAS N
         INNER JOIN ITENS_NOTAS ITN ON ITN.NUMERO = N.NUMERO
GROUP BY N.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;



CREATE TRIGGER TG_TAB_FATURAMENTO
    AFTER INSERT ON ITENS_NOTAS
BEGIN
    DELETE FROM TAB_FATURAMENTO WHERE FATURAMENTO >= 0;

    INSERT INTO TAB_FATURAMENTO
    SELECT N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
    FROM NOTAS N
             INNER JOIN ITENS_NOTAS ITN ON ITN.NUMERO = N.NUMERO
    GROUP BY N.DATA_VENDA;

END;



-- DROP TRIGGER nome_trigger

CREATE OR REPLACE TRIGGER TG_TAB_FATURAMENTO
    AFTER INSERT OR UPDATE OR DELETE ON ITENS_NOTAS
BEGIN
    DELETE FROM TAB_FATURAMENTO WHERE FATURAMENTO >= 0;

    INSERT INTO TAB_FATURAMENTO
    SELECT N.DATA_VENDA, SUM(ITN.QUANTIDADE * ITN.PRECO) AS FATURAMENTO
    FROM NOTAS N
             INNER JOIN ITENS_NOTAS ITN ON ITN.NUMERO = N.NUMERO
    GROUP BY N.DATA_VENDA;

END;

commit;
